userressources=$HOME/.Xresources

if [ -f $userressources ]; then
	xrdb -merge .Xresources
fi

sh .screenlayout/triple_monitor.sh
feh --bg-fill -g 3440x1440 ~/.background.jpg
xmodmap .Xmodmap
xinput set-prop pointer:"Logitech Wireless Mouse MX Master 3"  "Coordinate Transformation Matrix" 2.5 0 0 0 2.5 0 0 0 1
exec i3

