userressources=$HOME/.Xresources

if [ -f $userressources ]; then
	xrdb -merge .Xresources
fi

sh .config/screenlayout/triple_monitor.sh
sh .config/wacom/setup.sh
feh --bg-fill -g 3440x1440 ~/.background.jpg
xmodmap .Xmodmap
exec i3

