# ZSH base configuration
HISTFILE=~/.histfile
HISTSIZE=4096
SAVEHIST=4096
setopt autocd extendedglob nomatch
bindkey -e
zstyle :compinstall filename '/home/math/.zshrc'
fpath+=/home/math/miniconda3/conda-zsh-completion
autoload -Uz compinit && compinit
export EDITOR=code
stty -ixon  # Allows backward cycling in reverse-search.

# Keybinding
typeset -g -A key
key[Insert]="${terminfo[kich1]}"
key[Delete]="${terminfo[kdch1]}"
key[Shift-Tab]="${terminfo[kcbt]}"
# setup key accordingly
[[ -n "${key[Insert]}"    ]] && bindkey -- "${key[Insert]}"    overwrite-mode
[[ -n "${key[Delete]}"    ]] && bindkey -- "${key[Delete]}"    delete-char
[[ -n "${key[Shift-Tab]}" ]] && bindkey -- "${key[Shift-Tab]}" reverse-menu-complete

# Word navigation
bindkey "^B" backward-word
bindkey "^F" forward-word
bindkey "^u" backward-kill-line

# Prompt appearance
PROMPT='%n@%m %(?.%F{green}√.%F{red}?%?)%f %B%F{blue}%1~%f%b %# '
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%F{magenta}(%b)%r%f'
zstyle ':vcs_info:*' enable git

# SSH Keys loading
eval `keychain --eval --quiet`
function ssh-persist {
    eval $(keychain --eval --quiet --confhost $1)
}

# Basic config
export PATH=~/bin:$PATH
export MAKEFLAGS="-j$(nproc)"

# Aliases
alias c='clear'

alias l=ls
alias sl='ls'
alias ls='ls -Fh --color=auto'
alias la='ls -a'
alias ll='ls -la'

alias mv='mv -i'
alias cp='cp -i'
alias mkdir='mkdir -pv'

alias grep='grep --color=auto'

# Functions
lb-eosr6() {
    screen -S lb-eosr6 -dm bash -c \
    'gphoto2 --set-config-value whitebalance="Auto" && \
    gphoto2 --stdout --capture-movie | \
    ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video4 \
    -nostdin -loglevel panic 2> /dev/null&'
}
lb-eosr6-kill() {
    screen -XS lb-eosr6 quit
}
lb-streamcam(){
    screen -S lb-streamcam -dm bash -c \
    'ffmpeg -f v4l2 -c:v mjpeg -r 60 -video_size 1920x1080 -i /dev/video0 -pix_fmt yuyv422 -f v4l2 /dev/video3'
}
lb-streamcam-kill(){
    screen -XS lb-streamcam quit
}

# Go
export GOPATH=$HOME/go
export PATH=~/go/bin:$PATH

# Python
alias py=python
export PIP_REQUIRE_VIRTUALENV=true
export PYVINIT="blacken-docs flake8-docstrings pytest pre-commit mypy"

# NPM
export PATH=~/.npm-global/bin/:$PATH

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/math/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/math/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/math/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/math/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
export TERMINFO=/usr/share/terminfo

