# ZSH base configuration
HISTFILE=~/.histfile
HISTSIZE=4096
SAVEHIST=4096
setopt autocd extendedglob nomatch
bindkey -e
zstyle :compinstall filename '/home/math/.zshrc'
autoload -Uz compinit && compinit
export EDITOR=code
stty -ixon  # Allows backward cycling in reverse-search.

# Keybinding
typeset -g -A key
key[Insert]="${terminfo[kich1]}"
key[Delete]="${terminfo[kdch1]}"
key[Shift-Tab]="${terminfo[kcbt]}"
# setup key accordingly
[[ -n "${key[Insert]}"    ]] && bindkey -- "${key[Insert]}"    overwrite-mode
[[ -n "${key[Delete]}"    ]] && bindkey -- "${key[Delete]}"    delete-char
[[ -n "${key[Shift-Tab]}" ]] && bindkey -- "${key[Shift-Tab]}" reverse-menu-complete

# Word navigation
bindkey "^B" backward-word
bindkey "^F" forward-word
bindkey "^u" backward-kill-line

# Prompt appearance
PROMPT='%(?.%F{green}√.%F{red}?%?)%f %B%F{blue}%1~%f%b %# '
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%F{magenta}(%b)%r%f'
zstyle ':vcs_info:*' enable git

# SSH Keys loading
eval `keychain --eval --quiet`
function ssh-persist {
    eval $(keychain --eval --quiet --confhost $1)
}

# Basic config
export PATH=~/bin:$PATH
export MAKEFLAGS="-j$(nproc)"

# Aliases
alias c='clear'

alias l=ls
alias sl='ls'
alias ls='ls -GFh --color=auto'
alias ll='ls -la'

alias mv='mv -i'
alias cp='cp -i'
alias mkdir='mkdir -pv'

alias grep='grep --color=auto'

# Go
export GOPATH=$HOME/go

# Python
alias py=python
export PIP_REQUIRE_VIRTUALENV=true
export PYVINIT="blacken-docs flake8-docstrings pytest pre-commit mypy"

# NPM
export PATH=~/.npm-global/bin/:$PATH

